#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fManager
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ORDERMILKTEA")]
	public partial class DataClassesXuatHoadonDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClassesXuatHoadonDataContext() : 
				base(global::fManager.Properties.Settings.Default.ORDERMILKTEAConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesXuatHoadonDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesXuatHoadonDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesXuatHoadonDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesXuatHoadonDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.USP_GetListBillByDate")]
		public ISingleResult<USP_GetListBillByDateResult> USP_GetListBillByDate([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> checkIn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> checkOut)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), checkIn, checkOut);
			return ((ISingleResult<USP_GetListBillByDateResult>)(result.ReturnValue));
		}
	}
	
	public partial class USP_GetListBillByDateResult
	{
		
		private string _Tên_bàn;
		
		private System.Nullable<double> _Tổng_tiền;
		
		private System.DateTime _Ngày_vào;
		
		private System.Nullable<System.DateTime> _Ngày_ra;
		
		private System.Nullable<int> _Giảm_giá;
		
		public USP_GetListBillByDateResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tên bàn]", Storage="_Tên_bàn", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Tên_bàn
		{
			get
			{
				return this._Tên_bàn;
			}
			set
			{
				if ((this._Tên_bàn != value))
				{
					this._Tên_bàn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tổng tiền]", Storage="_Tổng_tiền", DbType="Float")]
		public System.Nullable<double> Tổng_tiền
		{
			get
			{
				return this._Tổng_tiền;
			}
			set
			{
				if ((this._Tổng_tiền != value))
				{
					this._Tổng_tiền = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Ngày vào]", Storage="_Ngày_vào", DbType="Date NOT NULL")]
		public System.DateTime Ngày_vào
		{
			get
			{
				return this._Ngày_vào;
			}
			set
			{
				if ((this._Ngày_vào != value))
				{
					this._Ngày_vào = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Ngày ra]", Storage="_Ngày_ra", DbType="Date")]
		public System.Nullable<System.DateTime> Ngày_ra
		{
			get
			{
				return this._Ngày_ra;
			}
			set
			{
				if ((this._Ngày_ra != value))
				{
					this._Ngày_ra = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Giảm giá]", Storage="_Giảm_giá", DbType="Int")]
		public System.Nullable<int> Giảm_giá
		{
			get
			{
				return this._Giảm_giá;
			}
			set
			{
				if ((this._Giảm_giá != value))
				{
					this._Giảm_giá = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
